version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: excel_testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
